### ISSUE TITLE
Specific question and can't find examples

### ISSUE THREAD

**Issue by Mikelius45** [McJtyMods/Wastify#5]
Hey, thanks for your mod and support!

So my goal is to fill all the air and cave_air blocks under y level 64 with water in world gen.
I don't really get how I can modify the overworld.json to change a block in world gen, so even less if it is even possible to do it with a y level condition.

That would be really amazing! I'm in 1.19.2.

Thanks

**Comment by McJty** [comment]
That's not something Wastify can do but check out: https://misode.github.io/worldgen/noise-settings/?version=1.20&preset=overworld
That tool can help you generate the correct jsons

**Comment by Mikelius45** [comment]
Oh great thank you so much!
I'll check it out. So it's to use with a mod or as a datapack?

**Comment by McJty** [comment]
Datapack
